language: go

go:
  - 1.11
  - 1.12
  - 1.13
  - 1.14
  - tip

services:
  - zap-api-go

before_install:
  - go get -v golang.org/x/lint

script:
  - ./pre-commit
  #TODO: enable this when we have test files
  #- go test -cpu=1,2 -v -tags integration ./...